global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: IOT
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets:
        - flask-app:5000 # equivalent to "localhost:9090"
