global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: json_exporter
    scrape_interval: 20s
    scrape_timeout: 10s
    honor_labels: true
    metrics_path: /probe
    static_configs:
      - targets:
          - http://flask-app:5000/all_json
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: json_exporter:7979