modules:
  default:
    headers:
      MyHeader: MyHeaderValue
    metrics:
      - name: time
        type: object
        help: timeeee
        path: '{}'
        values:
          Time: '{.Time}'
      - name: temp
        type: object
        help: temperature
        path: '{}'
        values:
          Temp: '{.Temperature}'
      - name: hum
        type: object
        help: hummmm
        path: '{}'
        values:
          Hum: '{.Humidity}'
      - name: ec
        type: object
        help: ec
        path: '{}'
        values:
          Ec: '{.Ec}'
      - name: ph
        type: object
        help: ph
        path: '{}'
        values:
          Ph: '{.Ph}'

http_client_config:
  tls_config:
    insecure_skip_verify: true