---
modules:
  IOT:
    metrics:
    - name: time
      type: value
      help: time
      path: '{ $.Time }'
    - name: Temperature
      type: value
      help: Temperature
      path: '{ $.Temperature }'
    - name: Humidity
      type: value
      help: Humidity
      path: '{ $.Humidity }'
    - name: Ec
      type: value
      help: Ec
      path: '{ $.Ec }'
    - name: Ph
      type: value
      help: Ph
      path: '{ $.Ph }'