modules:
  default:
    headers:
      MyHeader: MyHeaderValue
    metrics:
      - name: cryptocurrency
        type: object
        help: General statistics of the top cryptocurrencies
        path: '{}'
        values:
          Ec: '{.Ec}'

http_client_config:
  tls_config:
    insecure_skip_verify: true