---
modules:
  animals:
    metrics:
    - name: time
      type: object
      help: time
      path: '{ .Time }'
      values:
        time: '{ .Time }'
    - name: Temperature
      type: object
      help: Temperature
      path: '{ .Temperature }'
      values:
        Temperature: '{ .Temperature }'
    - name: Humidity
      type: object
      help: Humidity
      path: '{ .Humidity }'
      values:
        Humidity: '{ .Humidity }'
    - name: Ec
      type: object
      help: Ec
      path: '{ .Ec }'
      values:
        Ec: '{ .Ec }'
    - name: Ph
      type: object
      help: Ph
      path: '{ .Ph }'
      values:
        Ph: '{ .Ph }'