modules:
  default:
    headers:
      MyHeader: MyHeaderValue
    metrics:
      - name: cryptocurrency
        type: object
        help: General statistics of the top cryptocurrencies
        path: '{}'
        values:
          Ec: '{.Ec}'