---
modules:
  animals:
    metrics:
    - name: animal
      type: object
      help: Example of top-level lists in a separate module
      path: '{*}'
      labels:
        name: '{ .Ec }'
        predator: '{ .Ph }'
      values:
        population: '{ .Ec }'