listenAddress: ":7979"
metricsPath: "/metrics"
logLevel: "info"

scrapeConfigs:
  - jobName: "json_endpoint"
    json:
      endpoint: "https://www.terjack.space/all_json"
      requestType: "GET"
      interval: "30s"
      headers:
        User-Agent: "json_exporter"
    metrics:
      - name: "Ec"
        path: "$.Ec"
        type: "gauge"
        help: "EC value"
      - name: "Humidity"
        path: "$.Humidity"
        type: "gauge"
        help: "Humidity value"
      - name: "Temperature"
        path: "$.Temperature"
        type: "gauge"
        help: "Temperature value"
      - name: "Ph"
        path: "$.Ph"
        type: "gauge"
        help: "Ph value"