modules:
  - name: sample_json_metrics
    port: 7979
    path: /metrics

    targets:
      - name: sample_json
        url: https://www.terjack.space/all_json
        method: GET

        labels:
          environment: production
          job: json_metrics